var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import { styled } from 'twin.macro';
export var RundownThemeMap = {
    default: '#F5F5F5',
    blue: '#0266D3',
};
export var BorderWidthMap = {
    none: '0px',
    sm: '2px',
    md: '4px',
    lg: '8px',
};
export var RundownContainer = styled.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n    display: flex;\n    flex-direction: column;\n    align-items: center;\n    justify-content: center;\n    width: 100%;\n    max-width: 1124px;\n    @media (min-width: 768px) {\n        justify-content: start;\n        align-items: flex-start;\n    }\n"], ["\n    display: flex;\n    flex-direction: column;\n    align-items: center;\n    justify-content: center;\n    width: 100%;\n    max-width: 1124px;\n    @media (min-width: 768px) {\n        justify-content: start;\n        align-items: flex-start;\n    }\n"])));
export var StyledRundown = styled.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n    margin-top: 0.5rem;\n    margin-bottom: 0.5rem;\n    border: none;\n    display: flex;\n    flex-wrap: wrap;\n    border-radius: 1rem;\n    padding: 28px 24px 28px 24px;\n    align-items: center;\n    background-color: ", ";\n    width: 100%;\n    font-weight: 700;\n    font-size: 1.125rem;\n    @media (max-width: 768px) {\n        justify-content: center;\n        padding: 1rem;\n    }\n"], ["\n    margin-top: 0.5rem;\n    margin-bottom: 0.5rem;\n    border: none;\n    display: flex;\n    flex-wrap: wrap;\n    border-radius: 1rem;\n    padding: 28px 24px 28px 24px;\n    align-items: center;\n    background-color: ", ";\n    width: 100%;\n    font-weight: 700;\n    font-size: 1.125rem;\n    @media (max-width: 768px) {\n        justify-content: center;\n        padding: 1rem;\n    }\n"])), function (props) { return RundownThemeMap[props.backgroundColor]; });
export var StyledTime = styled.div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n    width: auto;\n    display: flex;\n    align-items: center;\n    height: 3.5rem;\n    justify-content: center;\n    margin-right: 2.75rem;\n    border-radius: 1rem;\n    font-size: 1rem;\n    font-weight: 600;\n    margin-left: 0;\n    background-color: ", ";\n    color: ", ";\n    padding-left: 0.75rem;\n    padding-right: 0.75rem;\n    padding-top: 0.5rem;\n    padding-bottom: 0.5rem;\n    @media (max-width: 768px) {\n        width: 100%;\n        display: flex;\n        justify-content: center;\n        margin-right: 0;\n        margin-bottom: 0.5625rem;\n        height: 2.375rem;\n        border-radius: 10px;\n    }\n    @media (min-width: 768px) {\n        min-height: 3rem;\n        min-width: 12rem;\n        max-width: 16rem;\n    }\n"], ["\n    width: auto;\n    display: flex;\n    align-items: center;\n    height: 3.5rem;\n    justify-content: center;\n    margin-right: 2.75rem;\n    border-radius: 1rem;\n    font-size: 1rem;\n    font-weight: 600;\n    margin-left: 0;\n    background-color: ", ";\n    color: ", ";\n    padding-left: 0.75rem;\n    padding-right: 0.75rem;\n    padding-top: 0.5rem;\n    padding-bottom: 0.5rem;\n    @media (max-width: 768px) {\n        width: 100%;\n        display: flex;\n        justify-content: center;\n        margin-right: 0;\n        margin-bottom: 0.5625rem;\n        height: 2.375rem;\n        border-radius: 10px;\n    }\n    @media (min-width: 768px) {\n        min-height: 3rem;\n        min-width: 12rem;\n        max-width: 16rem;\n    }\n"])), function (props) { return props.timeBgColor; }, function (props) { return props.timeColor; });
export var StyledTimeIcon = styled.img(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n    margin-right: 0.375rem;\n"], ["\n    margin-right: 0.375rem;\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4;
//# sourceMappingURL=style.js.map