var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import { jsx as _jsx } from "react/jsx-runtime";
import { GlobalStyles, css } from 'twin.macro';
export var GlobalStylesConfig = function () {
    return (_jsx(GlobalStyles, { css: css(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n                html {\n                    scroll-behavior: smooth;\n                }\n\n                .body {\n                    font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu,\n                        Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;\n                }\n\n                button {\n                    cursor: pointer;\n                }\n                [role='button'] {\n                    cursor: pointer;\n                }\n\n                button[type='button'] {\n                    cursor: pointer;\n                }\n\n                button:focus {\n                    outline: none !important;\n                }\n\n                h1,\n                h2,\n                h3,\n                h4,\n                h5 {\n                    line-height: 1.25 rem;\n                }\n            "], ["\n                html {\n                    scroll-behavior: smooth;\n                }\n\n                .body {\n                    font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu,\n                        Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;\n                }\n\n                button {\n                    cursor: pointer;\n                }\n                [role='button'] {\n                    cursor: pointer;\n                }\n\n                button[type='button'] {\n                    cursor: pointer;\n                }\n\n                button:focus {\n                    outline: none !important;\n                }\n\n                h1,\n                h2,\n                h3,\n                h4,\n                h5 {\n                    line-height: 1.25 rem;\n                }\n            "]))) }, void 0));
};
var templateObject_1;
//# sourceMappingURL=global.styles.js.map