var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import { styled } from 'twin.macro';
export var RadioContainer = styled.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n    display: flex;\n    flex-direction: row;\n    column-gap: 1rem;\n    flex-wrap: wrap;\n\n    [type='radio'] {\n        opacity: 0;\n        width: 0;\n        height: 0;\n    }\n\n    /* IMAGE STYLES */\n    [type='radio'] + h1 {\n        cursor: pointer;\n    }\n\n    /* CHECKED STYLES */\n    [type='radio']:checked + h1 {\n        background-color: #0266d3;\n        color: white;\n    }\n"], ["\n    display: flex;\n    flex-direction: row;\n    column-gap: 1rem;\n    flex-wrap: wrap;\n\n    [type='radio'] {\n        opacity: 0;\n        width: 0;\n        height: 0;\n    }\n\n    /* IMAGE STYLES */\n    [type='radio'] + h1 {\n        cursor: pointer;\n    }\n\n    /* CHECKED STYLES */\n    [type='radio']:checked + h1 {\n        background-color: #0266d3;\n        color: white;\n    }\n"])));
export var StyledRadioButton = styled.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n    display: flex;\n    flex-direction: column;\n    justify-content: center;\n    align-items: center;\n"], ["\n    display: flex;\n    flex-direction: column;\n    justify-content: center;\n    align-items: center;\n"])));
export var StyledLabel = styled.label(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n    margin-top: -0.75rem;\n"], ["\n    margin-top: -0.75rem;\n"])));
export var StyledRadioText = styled.h1(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n    color: #0266d3;\n    background-color: #f6f6f6;\n    padding: 0.5rem 1rem 0.5rem 1rem;\n    border-radius: 1.5rem;\n    font-size: 0.875rem;\n    line-height: 1.25rem;\n    font-weight: 700;\n"], ["\n    color: #0266d3;\n    background-color: #f6f6f6;\n    padding: 0.5rem 1rem 0.5rem 1rem;\n    border-radius: 1.5rem;\n    font-size: 0.875rem;\n    line-height: 1.25rem;\n    font-weight: 700;\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4;
//# sourceMappingURL=style.js.map