# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    paths: ["src/stories/**", "src/components/**"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and deploy to storybook-static branch
      uses: JamesIves/github-pages-deploy-action@2.0.3
      env:
        ACCESS_TOKEN: ${{ secrets.BDOUGIE_TOKEN }}
        BRANCH: main
        FOLDER: build
        BUILD_SCRIPT: npm install && npm run build-storybook
